name       : usbutils
version    : 009
release    : 4
source     :
    - https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-009.tar.xz : 8bbff0e54cb5f65a52be4feb9162fc0b022a97eb841b44784f7a89a9ea567160
homepage   : http://linux-usb.sourceforge.net/
license    : GPL-2.0
summary    : usbutils (USB Utilities)
component  : system.base
builddeps  :
    - pkgconfig(libusb-1.0)
description: |
    usbutils provides userland utilities for USB devices under Linux.
setup      : |
    %configure --disable-zlib \
               --datadir=/usr/share/hwdata \
               --disable-usbids
build      : |
    %make
install    : |
    %make_install
    # Don't need this
    rm -rvf $installdir/%libdir%
