name       : usbutils
version    : '013'
release    : 7
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/usb/usbutils/usbutils-013.tar.xz : 9e23494fcc78b7a80ee29a07dd179c95ae2f71509c35728dbbabc2d1cca41338
homepage   : http://www.linux-usb.org/
license    : GPL-2.0-or-later
component  : system.base
summary    : usbutils (USB Utilities)
description: |
    usbutils provides userland utilities for USB devices under Linux.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %autogen --disable-zlib \
             --datadir=/usr/share/hwdata \
             --disable-usbids
build      : |
    %make
install    : |
    %make_install

    # Don't need this
    rm -rvf $installdir/%libdir%
