name       : usbutils
version    : '010'
release    : 5
source     :
    - https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-010.tar.xz : 61c7364bb4986fb05e5067e4ac5585b1299b664c57f761caecd2e9e724794a19
homepage   : http://www.linux-usb.org/
license    : GPL-2.0-or-later
component  : system.base
summary    : usbutils (USB Utilities)
description: |
    usbutils provides userland utilities for USB devices under Linux.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %configure --disable-zlib \
               --datadir=/usr/share/hwdata \
               --disable-usbids
build      : |
    %make
install    : |
    %make_install

    # Don't need this
    rm -rvf $installdir/%libdir%
