name       : usbutils
version    : 008
release    : 3
source     :
    - https://www.kernel.org/pub/linux/utils/usb/usbutils/usbutils-008.tar.xz : 44741af0bae9d402a0ef160a29b2fa700bb656ab5e0a4b3343d51249c2a44c8c
homepage   : http://linux-usb.sourceforge.net/
license    : GPL-2.0
summary    : usbutils (USB Utilities)
component  : system.base
builddeps  :
    - pkgconfig(libusb-1.0)
description: |
    usbutils provides userland utilities for USB devices under Linux.
setup      : |
    %patch -p1 < $pkgfiles/usbutils-006-hwdata.patch
    %configure --disable-zlib \
               --datadir=/usr/share/hwdata \
               --disable-usbids
build      : |
    %make
install    : |
    %make_install
    # Don't need this
    rm -rvf $installdir/usr/share/pkgconfig
