name       : usbutils
version    : '014'
release    : 8
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/usb/usbutils/usbutils-014.tar.xz : 3a079cfad60560227b67192482d7813bf96326fcbb66c04254839715f276fc69
homepage   : http://www.linux-usb.org/
license    : GPL-2.0-or-later
component  : system.base
summary    : usbutils (USB Utilities)
description: |
    usbutils provides userland utilities for USB devices under Linux.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %reconfigure --disable-zlib \
        --datadir=/usr/share/hwdata \
        --disable-usbids
build      : |
    %make
install    : |
    %make_install

    # Don't need this
    rm -rvf $installdir/%libdir%
