name       : usbutils
version    : '012'
release    : 6
source     :
    - https://mirrors.edge.kernel.org/pub/linux/utils/usb/usbutils/usbutils-012.tar.xz : 88634625f91840bc1993d2731cc081ee8d3b13d56069a95bdd6ac6ef0e063e46
homepage   : http://www.linux-usb.org/
license    : GPL-2.0-or-later
component  : system.base
summary    : usbutils (USB Utilities)
description: |
    usbutils provides userland utilities for USB devices under Linux.
builddeps  :
    - pkgconfig(libusb-1.0)
setup      : |
    %autogen --disable-zlib \
             --datadir=/usr/share/hwdata \
             --disable-usbids
build      : |
    %make
install    : |
    %make_install

    # Don't need this
    rm -rvf $installdir/%libdir%
